export enum Nodes {
  ROUTER = "ROUTER",
  GENERAL = "GENERAL",
  GATHER_REQUIREMENTS = "GATHER_REQUIREMENTS",
  GENERATE_QUERY = "GENERATE_QUERY",
  IS_VALID_QUERY = "IS_VALID_QUERY",
  EXECUTE_QUERY = "EXECUTE_QUERY",
  SUMMARIZE_RESPONSE = "SUMMARIZE_RESPONSE",
}
