export enum Nodes {
  INIT_PLAYERS = "INIT_PLAYERS",
  NARRATOR = "NARRATOR",

  DAY_PHASE = "DAY_PHASE",

  NIGHT_PHASE = "NIGHT_PHASE",
  DOCTOR = "DOCTOR",
  DETECTIVE = "DETECTIVE",

  START_DISCUSSION = "START_DISCUSSION",

  DISCUSSION = "DISCUSSION",
  ADD_TO_DISCUSSION = "ADD_TO_DISCUSSION",
  RESPOND_TO_DISCUSSION = "RESPOND_TO_DISCUSSION",
  VOTE = "VOTE",
  TALLY_VOTES = "TALLY_VOTES",
  CHECK_CONSENSUS = "CHECK_CONSENSUS",
  RESOLVE_VOTE = "RESOLVE_VOTE",
  END_DISCUSSION = "END_DISCUSSION",
}
