export enum Nodes {
  GENERATE_PLAN = "GENERATE_PLAN",
  REVIEW_PLAN = "REVIEW_PLAN",
  ASSIGN_TASK = "ASSIGN_TASK",
  EXECUTE_TASK = "EXECUTE_TASK",
  REVIEW_OUTPUT = "REVIEW_OUTPUT",

  WEB_SEARCH = "WEB_SEARCH",
  SQL_SEARCH = "SQL_SEARCH",

  SUMMARIZE_RESULTS = "SUMMARIZE_RESULTS",
}

export const MAX_NUM_STEPS = 10;
